https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv

In [2]:
import pandas as pd

In [3]:
url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"
df = pd.read_csv(url)
df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [4]:
#limpieza de datos
siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

siniestros['fecha_siniestro'] = pd.to_datetime(siniestros['fecha_siniestro'], errors='coerce')

siniestros['monto_siniestro'] = siniestros['monto_siniestro'].replace(['N/A', '-'], pd.NA)
siniestros['monto_siniestro'] = siniestros['monto_siniestro'].astype(str).str.replace(",", "", regex=False)
siniestros['monto_siniestro'] = pd.to_numeric(siniestros['monto_siniestro'], errors='coerce')

siniestros['estado'] = siniestros['estado'].str.upper().str.strip()

siniestros = siniestros.drop_duplicates()

/tmp/ipykernel_23229/3814216379.py:11: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros['fecha_siniestro'] = pd.to_datetime(siniestros['fecha_siniestro'], errors='coerce')

In [5]:
#Separar datos válidos y rechazados
validos = siniestros[
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna() &
    siniestros['estado'].notna()
].copy()

rechazados = siniestros[
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna() |
    siniestros['estado'].isna()
].copy()

In [6]:
#motivo de rechazo
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_vacia")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_vacio")

    if pd.isna(row['estado']):
        motivos.append("estado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [7]:
#Exportar archivos
validos.to_csv("Siniestros_curated.csv", index=False)

rechazados.to_csv("siniestros_rejects.csv", index=False)

In [8]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [9]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd



database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"
engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 66.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

   ?column?
0         1

In [10]:
validos.to_sql('siniestros_curated', engine, if_exists='append', index=False)

rechazados.to_sql('siniestros_rejects', engine, if_exists='append', index=False)

881

In [11]:
pd.read_sql("SELECT * FROM siniestros_curated LIMIT 10", engine)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    ABIERTO
1             3      15785      2025-09-19           702.27    CERRADO
2             8      23824      2025-01-17          2736.20    ABIERTO
3            13       3716      2025-07-13         -4274.39  RECHAZADO
4            24      17180      2025-06-13          6183.83    CERRADO
5            27      22625      2025-03-07           141.77        NAN
6            33       2231      2025-09-21          2443.90  RECHAZADO
7            36      16929      2025-01-06          3649.94    CERRADO
8            45      15100      2025-01-27          8761.24    ABIERTO
9            66      14064      2025-03-25          9842.05    ABIERTO