https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv

In [1]:
import pandas as pd

In [2]:
url="https://raw.githubusercontent.com/JUAN-32/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"
df = pd.read_csv(url)
df.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [3]:
#Limpieza de datos
tipo_seguro = df.copy()

tipo_seguro.columns = tipo_seguro.columns.str.strip().str.lower()

for col in tipo_seguro.select_dtypes(include='object').columns:
    tipo_seguro[col] = tipo_seguro[col].astype(str).str.strip()

tipo_seguro = tipo_seguro.replace(r'^\s*$', pd.NA, regex=True)

tipo_seguro['tipo'] = tipo_seguro['tipo'].str.title()
tipo_seguro['categoria'] = tipo_seguro['categoria'].str.title()

tipo_seguro['tipo'] = tipo_seguro['tipo'].replace({
    'Educaciã³n': 'Educación',
    'Agrã­cola': 'Agrícola'
})

tipo_seguro['riesgo_base'] = tipo_seguro['riesgo_base'].replace(['N/A', '-'], pd.NA)
tipo_seguro['riesgo_base'] = pd.to_numeric(tipo_seguro['riesgo_base'], errors='coerce')

tipo_seguro = tipo_seguro.drop_duplicates()

In [4]:
#Separacion de datos valios y Rechazados
validos = tipo_seguro[
    tipo_seguro['tipo'].notna() &
    tipo_seguro['categoria'].notna() &
    tipo_seguro['riesgo_base'].notna()
].copy()

rechazados = tipo_seguro[
    tipo_seguro['tipo'].isna() |
    tipo_seguro['categoria'].isna() |
    tipo_seguro['riesgo_base'].isna()
].copy()

In [5]:
#motivo de rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['tipo']):
        motivos.append("tipo_vacio")

    if pd.isna(row['categoria']):
        motivos.append("categoria_vacio")

    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [6]:
#exportacion del archivo
validos.to_csv("tipo_seguro_curated.csv", index=False)

rechazados.to_csv("tipo_seguro_rejects.csv", index=False)

In [7]:
#revision de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

In [8]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://juan:7RwRd1YakvKS4tuz3o1p6rzxu8niaaeG@dpg-d6qu7h4hg0os73b4gn0g-a.oregon-postgres.render.com/etl_seguros_hhfg"

engine = create_engine(database_url)

pd.read_sql("SELECT 1", engine)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

   ?column?
0         1

In [9]:
validos.to_sql(
    'tipo_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'tipo_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

3

In [10]:
pd.read_sql(
    "SELECT * FROM tipo_seguro_curated LIMIT 10",
    engine
)

   id_tipo_seguro        tipo    categoria  riesgo_base
0               2  Industrial  Empresarial         4.68
1               3  Industrial     Familiar         5.10
2               5        Auto  Empresarial         9.07
3               6  Industrial  Empresarial         2.52
4               7       Salud     Personal         0.92
5               8   Educación  Empresarial         7.42
6               9  Accidentes          Nan         5.68
7              10      Dental     Especial         2.70
8              11        Auto  Empresarial         4.33